### ISSUE TITLE
Load additional browser driver

### ISSUE THREAD

**Issue by hypery2k** [hypery2k/galenframework-cli#13]
Would be nice besides the galen framework to download all needed [browser extensions](http://www.seleniumhq.org/download/), e.g. ChromeDriver and Safari Extension

**Comment by hypery2k** [comment]
Status
- [x] Chrome via ChromeDriver
- [ ] Safari
- [ ] IE

**Comment by lo1tuma** [comment]
To be honest, this is really annoying.

I run my tests against saucelabs, so I don’t  need additional browser drivers. Additionally installing `ChromeDriver` is flaky and my CI build randomly fails because  `ChromeDriver` can’t be installed. Since I updated to `2.0.8` a few days ago I’ve noticed that on my local developer machine (macbook) during `npm install` safari opens and ask me to import settings from chrome.

Would it be possible to publish a separate npm package without additional drivers?

**Comment by hypery2k** [comment]
I will provide an option to skip the install with the next version

**Comment by lo1tuma** [comment]
Awesome, thank you!

**Comment by hypery2k** [comment]
I've created a new version without driver installation, see https://github.com/hypery2k/galenframework-cli/releases/tag/v2.0.10

I will work on a options flag for installing the drivers

**Comment by lo1tuma** [comment]
Thank you :beers:.

**Comment by hypery2k** [comment]
With the next release there will be a core NPM module without driver installation. I will post here if it's available

**Comment by hypery2k** [comment]
Version 2.1.3 of the node modules are available.
There's a [core](https://www.npmjs.com/package/galenframework) module, which just downloads galen and [cli](https://www.npmjs.com/package/galenframework-cli) module which makes galen available as command with browser drivers.
